/*
 * drawable.c - drawable functions
 *
 * Copyright © 2008-2009 Julien Danjou <julien@danjou.info>
 * Copyright © 2010-2012 Uli Schlachter <psychon@znc.in>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 */

/** Low-level API for Skia-backed clients and wiboxes.
 *
 * @author Uli Schlachter &lt;psychon@znc.in&gt;
 * @copyright 2012 Uli Schlachter
 * @coreclassmod drawable
 */

#include "drawable.h"
#include "common/luaobject.h"
#include "common/xutil.h"
#include "globalconf.h"

#include <xcb/xcb_aux.h>

/** Drawable object.
 *
 * @property image
 * @tparam image image
 * @propertydefault Autogenerated.
 */

/**
 * @signal button::press
 */

/**
 * @signal button::release
 */

/**
 * @signal mouse::enter
 */

/**
 * @signal mouse::leave
 */

/**
 * @signal mouse::move
 */

/**
 * @signal property::geometry
 */

/**
 * @signal property::height
 */

/**
 * @signal property::width
 */

/**
 * @signal property::x
 */

/**
 * @signal property::y
 */

/**
 * @signal property::surface
 */

/** Get the number of instances.
 *
 * @return The number of drawable objects alive.
 * @staticfct instances
 */

/* Set a __index metamethod for all drawable instances.
 * @tparam function cb The meta-method
 * @staticfct set_index_miss_handler
 */

/* Set a __newindex metamethod for all drawable instances.
 * @tparam function cb The meta-method
 * @staticfct set_newindex_miss_handler
 */

static lua_class_t drawable_class;

LUA_OBJECT_FUNCS(drawable_class, drawable_t, drawable)

drawable_t *
drawable_allocator(lua_State *L, drawable_refresh_callback *callback, void *data,
                   xcb_window_t presentation_window)
{
    drawable_t *d = drawable_new(L);
    d->refresh_callback = callback;
    d->refresh_data = data;
    d->refreshed = false;
    d->pixmap = XCB_NONE;
    d->skia_renderer = NULL;
    d->skia_renderer_width = 0;
    d->skia_renderer_height = 0;
    d->skia_capacity_width = 0;
    d->skia_capacity_height = 0;
    d->skia_visible_width = 0;
    d->skia_visible_height = 0;
    d->skia_stable_backing = false;
    d->presentation_window = presentation_window;
    return d;
}

static void
drawable_unset_surface(drawable_t *d)
{
    if (d->skia_renderer)
        awesome_skia_renderer_destroy(d->skia_renderer);
    d->skia_renderer = NULL;
    d->skia_renderer_width = 0;
    d->skia_renderer_height = 0;
    d->skia_capacity_width = 0;
    d->skia_capacity_height = 0;
    if (d->pixmap)
        xcb_free_pixmap(globalconf.connection, d->pixmap);
    d->refreshed = false;
    d->pixmap = XCB_NONE;
}

static void
drawable_wipe(drawable_t *d)
{
    drawable_unset_surface(d);
}

void
drawable_ensure_renderer(drawable_t *d)
{
    if (d->geometry.width <= 0 || d->geometry.height <= 0)
        return;
    if (d->presentation_window == XCB_NONE)
        fatal("Skia drawable has no XCB presentation window");
    const uint16_t target_width = d->skia_stable_backing
                                ? d->skia_capacity_width : d->geometry.width;
    const uint16_t target_height = d->skia_stable_backing
                                 ? d->skia_capacity_height : d->geometry.height;
    if (d->skia_renderer && d->skia_renderer_width == target_width &&
        d->skia_renderer_height == target_height)
        return;

    /* A drawin's presentation child grows to its largest requested size but
     * never shrinks. Its logical parent clips it while the popup animates, so
     * Vulkan sees a stable native window and no per-frame swapchain rebuild.
     * Client titlebars continue to resize their presentation window normally.
     */
    if (d->skia_stable_backing)
        xcb_configure_window(globalconf.connection, d->presentation_window,
                             XCB_CONFIG_WINDOW_WIDTH | XCB_CONFIG_WINDOW_HEIGHT,
                             (const uint32_t []) { target_width, target_height });

    /* Ensure the final native size is visible to X11 WSI before creating or
     * growing the swapchain. This occurs once per new capacity, not once per
     * animation frame. */
    xcb_aux_sync(globalconf.connection);
    char error[256] = {0};
    if (d->skia_renderer) {
        if (!awesome_skia_renderer_resize(d->skia_renderer,
                                          target_width, target_height,
                                          error, sizeof(error)))
            fatal("Could not resize Skia/Vulkan drawable renderer: %s", error);
    } else {
        d->skia_renderer = awesome_skia_renderer_create(
            globalconf.connection, d->presentation_window,
            target_width, target_height, error, sizeof(error));
        if (!d->skia_renderer)
            fatal("Could not create required Skia/Vulkan drawable renderer: %s", error);
    }
    d->skia_renderer_width = target_width;
    d->skia_renderer_height = target_height;
}

void
drawable_set_geometry(lua_State *L, int didx, area_t geom)
{
    drawable_t *d = luaA_checkudata(L, didx, &drawable_class);
    area_t old = d->geometry;
    d->skia_visible_width = geom.width;
    d->skia_visible_height = geom.height;
    if (d->skia_stable_backing) {
        d->skia_capacity_width = MAX(d->skia_capacity_width, geom.width);
        d->skia_capacity_height = MAX(d->skia_capacity_height, geom.height);
        /* The outer drawin owns the animated logical bounds. Its presentation
         * child and widget hierarchy retain the largest size, so moving or
         * revealing a popup is an X clip/configure operation rather than a
         * Pango relayout and full Skia repaint on every tick. Keep x/y current
         * for screen lookup but do not signal redraws for position-only moves.
         */
        d->geometry = (area_t) {
            .x = geom.x,
            .y = geom.y,
            .width = d->skia_capacity_width,
            .height = d->skia_capacity_height
        };
    } else {
        d->skia_capacity_width = geom.width;
        d->skia_capacity_height = geom.height;
        d->geometry = geom;
    }

    const bool area_changed = !AREA_EQUAL(old, d->geometry);

    if (area_changed)
        luaA_object_emit_signal(L, didx, "property::geometry", 0);
    if (!d->skia_stable_backing && old.x != d->geometry.x)
        luaA_object_emit_signal(L, didx, "property::x", 0);
    if (!d->skia_stable_backing && old.y != d->geometry.y)
        luaA_object_emit_signal(L, didx, "property::y", 0);
    if (old.width != d->geometry.width)
        luaA_object_emit_signal(L, didx, "property::width", 0);
    if (old.height != d->geometry.height)
        luaA_object_emit_signal(L, didx, "property::height", 0);
}

static int
luaA_drawable_get_skia_renderer(lua_State *L, drawable_t *drawable)
{
    drawable_ensure_renderer(drawable);
    if (drawable->skia_renderer)
        lua_pushlightuserdata(L, drawable->skia_renderer);
    else
        lua_pushnil(L);
    return 1;
}

/** Refresh a drawable's content. This has to be called whenever some drawing to
 * the drawable's surface has been done and should become visible.
 *
 * @method refresh
 * @noreturn
 */
static int
luaA_drawable_refresh(lua_State *L)
{
    drawable_t *drawable = luaA_checkudata(L, 1, &drawable_class);
    drawable->refreshed = true;
    (*drawable->refresh_callback)(drawable->refresh_data);

    return 0;
}

/** Get drawable geometry. The geometry consists of x, y, width and height.
 *
 * @treturn table A table with drawable coordinates and geometry.
 * @method geometry
 */
static int
luaA_drawable_geometry(lua_State *L)
{
    drawable_t *d = luaA_checkudata(L, 1, &drawable_class);
    return luaA_pusharea(L, d->geometry);
}

/* The logical geometry of an animated drawin is its largest backing size so
 * layouts and its Vulkan swapchain remain stable. Expose the current outer
 * bounds separately to the Skia drawable code for conservative root culling. */
static int
luaA_drawable_skia_visible_size(lua_State *L)
{
    drawable_t *d = luaA_checkudata(L, 1, &drawable_class);
    lua_pushinteger(L, d->skia_visible_width);
    lua_pushinteger(L, d->skia_visible_height);
    return 2;
}

void
drawable_class_setup(lua_State *L)
{
    static const struct luaL_Reg drawable_methods[] =
    {
        LUA_CLASS_METHODS(drawable)
        { NULL, NULL }
    };

    static const struct luaL_Reg drawable_meta[] =
    {
        LUA_OBJECT_META(drawable)
        LUA_CLASS_META
        { "refresh", luaA_drawable_refresh },
        { "geometry", luaA_drawable_geometry },
        { "skia_visible_size", luaA_drawable_skia_visible_size },
        { NULL, NULL },
    };

    luaA_class_setup(L, &drawable_class, "drawable", NULL,
                     (lua_class_allocator_t) drawable_new,
                     (lua_class_collector_t) drawable_wipe, NULL,
                     luaA_class_index_miss_property, luaA_class_newindex_miss_property,
                     drawable_methods, drawable_meta);
    luaA_class_add_property(&drawable_class, "skia_renderer",
                            NULL,
                            (lua_class_propfunc_t) luaA_drawable_get_skia_renderer,
                            NULL);
}

/* @DOC_cobject_COMMON@ */

// vim: filetype=c:expandtab:shiftwidth=4:tabstop=8:softtabstop=4:textwidth=80
