#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Download, build, configure, and optionally run AwesomeWM's Skia/Vulkan
# renderer. Everything generated by this script lives under the user cache
# directory; it does not install or replace the system AwesomeWM.

set -Eeuo pipefail

usage() {
    cat <<'USAGE'
Usage: tools/bootstrap-skia-vulkan-probe.sh [--run] [--update] [--clean]

  --run       Run the diagnostic probe after the GPU-enabled Awesome build.
  --update    Fetch the requested Skia ref again before building.
  --clean     Delete this script's cached Skia and build directories, then exit.

Environment overrides:
  SKIA_REF                   Skia branch, tag, or commit (default: main)
  AWESOME_SKIA_CACHE_DIR     Cache/build root
  SKIA_EXTRA_LIBRARIES       Extra CMake libraries, separated by semicolons
  JOBS                       Parallel build jobs
USAGE
}

run_probe=0
update_skia=0
clean=0

while (($#)); do
    case "$1" in
        --run) run_probe=1 ;;
        --update) update_skia=1 ;;
        --clean) clean=1 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown argument: $1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cache_root="${AWESOME_SKIA_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/awesome-skia-probe}"
depot_tools_dir="$cache_root/depot_tools"
skia_dir="$cache_root/skia"
skia_out_rel="out/awesome-vulkan"
skia_out_dir="$skia_dir/$skia_out_rel"
awesome_build_dir="$cache_root/awesome-build"
skia_ref="${SKIA_REF:-main}"

if [[ "$clean" == 1 ]]; then
    rm -rf -- "$cache_root"
    echo "Removed $cache_root"
    exit 0
fi

for command in git python3 cmake pkg-config; do
    if ! command -v "$command" >/dev/null 2>&1; then
        echo "Missing required command: $command" >&2
        exit 1
    fi
done

cxx="${CXX:-}"
if [[ -z "$cxx" ]]; then
    if command -v clang++ >/dev/null 2>&1; then
        cxx=clang++
    elif command -v g++ >/dev/null 2>&1; then
        cxx=g++
    else
        echo "Missing a C++20 compiler (clang++ or g++)." >&2
        exit 1
    fi
fi

cc="${CC:-}"
if [[ -z "$cc" ]]; then
    if command -v clang >/dev/null 2>&1; then
        cc=clang
    elif command -v gcc >/dev/null 2>&1; then
        cc=gcc
    else
        echo "Missing a C compiler (clang or gcc)." >&2
        exit 1
    fi
fi

if ! printf '#include <vulkan/vulkan.h>\n' | "$cc" -E -x c - >/dev/null 2>&1; then
    echo "Vulkan development headers are missing (vulkan/vulkan.h)." >&2
    echo "Install your distribution's Vulkan development package and rerun." >&2
    exit 1
fi

if ! printf '#include <xcb/xcb.h>\n' | "$cc" -E -x c - >/dev/null 2>&1; then
    echo "XCB development headers are missing (xcb/xcb.h)." >&2
    echo "Install your distribution's XCB development package and rerun." >&2
    exit 1
fi

if command -v nproc >/dev/null 2>&1; then
    default_jobs="$(nproc)"
else
    default_jobs="$(getconf _NPROCESSORS_ONLN 2>/dev/null || printf '4')"
fi
jobs="${JOBS:-$default_jobs}"

mkdir -p "$cache_root"

if [[ ! -d "$depot_tools_dir/.git" ]]; then
    echo "Cloning depot_tools..."
    git clone --depth=1 \
        https://chromium.googlesource.com/chromium/tools/depot_tools.git \
        "$depot_tools_dir"
elif [[ "$update_skia" == 1 ]]; then
    echo "Updating depot_tools..."
    git -C "$depot_tools_dir" pull --ff-only
fi

export PATH="$depot_tools_dir:$PATH"

if [[ ! -d "$skia_dir/.git" ]]; then
    echo "Cloning Skia..."
    git clone --filter=blob:none --no-checkout \
        https://skia.googlesource.com/skia.git "$skia_dir"
    update_skia=1
fi

if [[ "$update_skia" == 1 ]] || ! git -C "$skia_dir" rev-parse --verify HEAD >/dev/null 2>&1; then
    echo "Fetching Skia ref: $skia_ref"
    git -C "$skia_dir" fetch --depth=1 origin "$skia_ref"
    git -C "$skia_dir" checkout --detach FETCH_HEAD
fi

printf 'Using Skia commit: '
git -C "$skia_dir" rev-parse --short=12 HEAD

(
    cd "$skia_dir"

    echo "Syncing Skia dependencies..."
    python3 tools/git-sync-deps

    if ! command -v ninja >/dev/null 2>&1; then
        echo "Fetching Ninja..."
        bin/fetch-ninja
        export PATH="$skia_dir/bin:$PATH"
    fi

    echo "Configuring Skia with Vulkan enabled..."
    bin/gn gen "$skia_out_rel" --args="\
is_official_build=true \
is_component_build=false \
skia_use_vulkan=true \
skia_use_gl=false"

    echo "Building Skia..."
    ninja -C "$skia_out_rel" -j "$jobs" skia
)

if ! command -v ninja >/dev/null 2>&1 && [[ -x "$skia_dir/bin/ninja" ]]; then
    export PATH="$skia_dir/bin:$PATH"
fi

skia_library="$skia_out_dir/libskia.a"
if [[ ! -f "$skia_library" ]]; then
    echo "Skia build completed, but $skia_library was not produced." >&2
    exit 1
fi

cmake_args=(
    -S "$repo_root"
    -B "$awesome_build_dir"
    -G Ninja
    -DWITH_SKIA_VULKAN=ON
    -DSKIA_SOURCE_DIR="$skia_dir"
    -DSKIA_LIBRARY="$skia_library"
    -DGENERATE_DOC=OFF
    -DGENERATE_MANPAGES=OFF
    -DCMAKE_C_COMPILER="$cc"
    -DCMAKE_CXX_COMPILER="$cxx"
)

if [[ -n "${SKIA_EXTRA_LIBRARIES:-}" ]]; then
    cmake_args+=("-DSKIA_EXTRA_LIBRARIES=${SKIA_EXTRA_LIBRARIES}")
fi

echo "Configuring the GPU-enabled AwesomeWM build..."
cmake "${cmake_args[@]}"

echo "Building AwesomeWM and skia-vulkan-probe..."
cmake --build "$awesome_build_dir" \
    --target awesome skia-vulkan-probe --parallel "$jobs"

probe="$awesome_build_dir/skia-vulkan-probe"
if [[ ! -x "$probe" ]]; then
    echo "Build succeeded, but the probe executable was not found at $probe" >&2
    exit 1
fi

echo
echo "GPU-enabled AwesomeWM built at: $awesome_build_dir/awesome"
echo "Probe built at: $probe"
echo "Nothing was installed and your normal AwesomeWM was not modified."

if [[ "$run_probe" == 1 ]]; then
    exec "$probe"
fi
